include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    dead_code: ignore
    depend_on_referenced_packages: ignore
    unnecessary_library_name: ignore
    unnecessary_null_comparison: ignore
    unused_element: ignore
    unused_local_variable: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
