name: auto_launcher
description: >
  A Flutter utility to automatically update the app's name, version,
  bundle identifiers, and app's icon across Android and iOS platforms.
version: 0.0.2
homepage:
repository: https://github.com/StartPackage/auto_launcher

platforms:
  android:
  ios:

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image: ^3.2.2
  archive: ^3.3.2
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
