name: auto_launcher
description: >
  A Flutter utility to automatically update the app's name, version,
  bundle identifiers, and launcher icon for Android and iOS. Ideal for CI/CD pipelines.
version: 0.0.3
homepage:
repository: https://github.com/StartPackage/auto_launcher

platforms:
  android:
  ios:

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  archive: ^4.0.7
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
